/*
SELECT *
FROM [Homelessness].[Reference].[tb_IgnoreCopyback]
WHERE Notes like 'April 2019 merger'
*/

--qname = qa_report_ref_data
SELECT TOP(10) [organisation-id]
      ,[OrganisationName]
      ,[TA-Q1-2018]
      ,[assess-tot-TQ]
      ,[assess-prev-TQ]
      ,[asess-rel-TQ]
      ,[end-prev-tot-TQ]
      ,[end-prev-accom-TQ]
      ,[end-prev-hless-TQ]
      ,[end-rel-tot-TQ]
      ,[end-rel-accom-TQ]
      ,[end-rel-56-TQ]
      ,[main-tot-TQ]
      ,[main-accept-TQ]
      ,[main-end-TQ]
      ,[main-end-sh-TQ]
      ,[main-end-prs-TQ]
      ,[TA-tot-HCLIC-TQ]
      ,[TA-tot-P1E-TQ]
      ,[TA-tot-comb-TQ]
      ,[TA-hhchild-HCLIC-TQ]
      ,[TA-hhchild-P1E-TQ]
      ,[TA-hhchild-comb-TQ]
      ,[TA-totchild-HCLIC-TQ]
      ,[TA-totchild-P1E-TQ]
      ,[TA-totchild-comb-TQ]
      ,[TA-BnBc-HCLIC-TQ]
      ,[TA-BnBc-P1E-TQ]
      ,[TA-BnBc-comb-TQ]
      ,[TA-BnB6w-HCLIC-TQ]
      ,[TA-BnB6w-P1E-TQ]
      ,[TA-BnB6w-comb-TQ]
      ,[TA-1617-HCLIC-TQ]
      ,[TA-1617-P1e-TQ]
      ,[TA-1617-comb-TQ]
      ,[DtR-adultsecure]
      ,[DtR-youthsecure]
      ,[DtR-childearlyhelp]
      ,[DtR-probation]
      ,[DtR-rehab]
      ,[DtR-hosp]
      ,[DtR-mentalhealth]
      ,[DtR-jobcentre]
      ,[DtR-adultsocial]
      ,[DtR-childsocial]
      ,[DtR-nilrec]
      ,[DtR-defence]
      ,[DtR-othernk]
      ,[assess-tot-PQ]
      ,[assess-prev-PQ]
      ,[assess-rel-PQ]
      ,[end-prev-tot-PQ]
      ,[end-prev-accom-PQ]
      ,[end-prev-hless-PQ]
      ,[end-rel-tot-PQ]
      ,[end-rel-accom-PQ]
      ,[end-rel-56-PQ]
      ,[main-tot-PQ]
      ,[main-accept-PQ]
      ,[main-end-tot-PQ]
      ,[main-end-sh-PQ]
      ,[main-end-prs-PQ]
      ,[TA-tot-comb-PQ]
      ,[TA-hhchild-comb-PQ]
      ,[TA-totchild-comb-PQ]
      ,[TA-BnBc-comb-PQ]
      ,[TA-BnB6w-comb-PQ]
      ,[TA-1617-HCLIC-PQ]
      ,[TA-1617-P1e-PQ]
      ,[TA-1617-comb-PQ]
      ,[assess-tot-PY]
      ,[assess-prev-PY]
      ,[assess-rel-PY]
      ,[end-prev-tot-PY]
      ,[end-prev-accom-PY]
      ,[end-prev-hless-PY]
      ,[end-rel-tot-PY]
      ,[end-rel-accom-PY]
      ,[end-rel-56-PY]
      ,[main-tot-PY]
      ,[main-accept-PY]
      ,[main-end-tot-PY]
      ,[main-end-sh-PY]
      ,[main-end-prs-PY]
      ,[TA-tot-comb-PY]
      ,[TA-hhchild-comb-PY]
      ,[TA-totchild-comb-PY]
      ,[TA-BnBc-comb-PY]
      ,[TA-BnB6w-comb-PY]
      ,[TA-1617-HCLIC-PY]
      ,[TA-1617-P1e-PY]
      ,[TA-1617-comb-PY]
      ,[date]
      INTO [Homelessness].[Analyse].[QA_Reports_{Sys.Date()}]
  FROM [Homelessness].[Analyse].[QA_Reports];

--qname = test
  SELECT TOP (10) *
  FROM [Homelessness].[Analyse].[QA_Reports_{Sys.Date()}];

--qname = delete
  DROP TABLE [Homelessness].[Analyse].[QA_Reports_{Sys.Date()}]

